### PR TITLE
add object related pipes

### PR DESCRIPTION
**Pull request by craigmichaelmartin**

### CODE REVIEW

**Comment by akersinformz** [comment]
Curious what is the use case for this pipe?

**Comment by craigmichaelmartin** [comment]
For iterating over an object with ngFor in angular's template expressions. Is there a better way?

Because I use the async pipe for streams (rather than explicitly subscribe), I don't have access to the value (an object) in a true javascript environment (angular's template expressions don't have access to `Object`).

**Comment by akersinformz** [comment]
I see.  You may want to add the ability to order the output.

**Comment by craigmichaelmartin** [comment]
Yep. I imagine I'll need that soon. Thanks!

**Pull request merged**
